USE [master]
GO

/****** Object:  Database [eStockMarketDB]    Script Date: 03-06-2022 12:54:35 ******/
DROP DATABASE [eStockMarketDB]
GO

/****** Object:  Database [eStockMarketDB]    Script Date: 03-06-2022 12:54:35 ******/
CREATE DATABASE [eStockMarketDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'eStockMarketDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\eStockMarketDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'eStockMarketDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\eStockMarketDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [eStockMarketDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [eStockMarketDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [eStockMarketDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [eStockMarketDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [eStockMarketDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [eStockMarketDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [eStockMarketDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [eStockMarketDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [eStockMarketDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [eStockMarketDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [eStockMarketDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [eStockMarketDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [eStockMarketDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [eStockMarketDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [eStockMarketDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [eStockMarketDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [eStockMarketDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [eStockMarketDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [eStockMarketDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [eStockMarketDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [eStockMarketDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [eStockMarketDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [eStockMarketDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [eStockMarketDB] SET RECOVERY FULL 
GO

ALTER DATABASE [eStockMarketDB] SET  MULTI_USER 
GO

ALTER DATABASE [eStockMarketDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [eStockMarketDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [eStockMarketDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [eStockMarketDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [eStockMarketDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [eStockMarketDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [eStockMarketDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [eStockMarketDB] SET  READ_WRITE 
GO

